let BingoCardDefaultOptions = [
  "Wins a crown in Fall Guys.",
  "MVP in Valorant.",
  "Gets a 'Victory Royale' in Fortnite.", 
  "They make me laugh.",
  "Is a V-Tuber.",
  "I can convince them to throw the game.",
  "I come across a stream that I follow.",
  "They convince me to follow them.",
  "They are playing a game I have never heard of.",
  "They have a donation goal.",
  "They say 'Poggers' unironically.",
  "Is objectively a better artist than me.",
  "ASMR stream with less than 10 viewers.",
  "Hot tub stream with less than 10 viewers.",
  "Sleeping stream with less than 10 viewers.", 
  "Charity Stream with less than 100 viewers.",
  "Girl streamer where camera is bigger than screen capture.",
  "I can convince them to end stream.",
  "Gets checkmated in chess.",
  "Gets a checkmate in chess.",
  "The stream is in the wrong category.",
  "Is playing guitar.",
  "DJ streamer has no epilepsy warning, but needs one.",
  "Someone gifts 25 or more subs while watching.",
  "Stream is 'Twitch Plays' themed.",
  "Ironic hot tub stream.",
  "Scuffed stream.",
  "Stream crashes.",
  "Stream has too much information on it.",
  "Streamer is toxic.",
  "Stream broadcasting a show or movie.",
  "Someone gifts a sub while watching.", 
  "BRB screen.",
  "IRL Stream.",
  "Some company watermark.",
  "Dies in game.",
  "Streamer's room is filthy.",
  "Streamer smokes weed on screen",
  "Has 69 or 420 viewers.",
  "Stream is way too loud.",
  "Has pet cam.",
  "V-Tuber model has boobie physics.",
  "Stream concept is unique or cool.",
  "Stream is WAY too quiet.",
  "Gets disqualified in Fall Guys.",
  "Streams makes me say 'WHY?'.", 
  "Is playing anime music in background.",
  "Has TTV in the name but has less than 5 viewers.",
  "Streamer is shirtless.", 
  "No face cam.",
  "No mic.",
  "Has a hand cam.",
  "Is trying to sell something.", 
  "Has drops enabled.", 
  "Makes a sexual inuendo.", 
  "Is speedrunning.", 
  "Their V-Tuber model breaks.", 
  "I can hear the streamer breathe.", 
  "Chair cam.", 
  "Has onlyfans command."
]
